### ISSUE TITLE
Create tag in the database if not exist

### ISSUE THREAD

**Issue by mrvahedi68** [pondersource/mfazones#4]
We create the tag in the constructor of the `Application` class as below:

https://github.com/pondersource/mfaverifiedzone/blob/924eb1803d940ee0d1c3d353151f60882ac4a0cf/lib/AppInfo/Application.php#L36

Is it ok to do this type of work in the constructor?

**Comment by navid-shokri** [comment]
you can create a public function in the Application class and call it inside the app.php file.

**Comment by mrvahedi68** [comment]
added on 924eb1803d940ee0d1c3d353151f60882ac4a0cf
